import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import StartupIdeaForm from "@/components/StartupIdeaForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AI Generated</title>
        <meta name="description" content="Generated by AI Generated" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex  justify-center items-center">
        <StartupIdeaForm></StartupIdeaForm>
      </main>
    </>
  );
}
